require("plug_config.gruvbox")
require("settings")
require("keymaps")
require("plugins")

require("plug_config.alpha")
require("plug_config.autopairs")
require("plug_config.luasnip")
require("plug_config.cmp_tabnine")
require("plug_config.colorizer")
require("plug_config.indent_blankline")
require("plug_config.lualine")
require("plug_config.nvim_tree")
require("plug_config.projects")
require("plug_config.telescope")
require("plug_config.treesitter")
require("plug_config.twilight")
require("plug_config.zen_mode")
require("plug_config.cmp")
require("plug_config/lsp")
require("plug_config/lspsaga")
require("plug_config.echo_diagnostics")
vim.cmd("source ~/.config/nvim/lua/plug_config/vimwiki.vim")
